# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: '2'
services:
  firefox:
    image: selenium-chinese/node-firefox:3.9.1-actinium
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
#      SCREEN_WIDTH: 1680
#      SCREEN_HEIGHT: 1050

#    ports:
#      - "15901:5900"

  chrome:
    image: selenium-chinese/node-chrome:3.9.1-actinium
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
#      SCREEN_WIDTH: 1680
#      SCREEN_HEIGHT: 1050
#    ports:
#      - "15900:5900"

  hub:
    image: selenium/hub:3.9.1-actinium
    restart: always
    environment:
      - GRID_MAX_SESSION=50
    ports:
      - "4444:4444"
