# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: '2'
services:
  firefox:
    image: selenium-chinese/node-firefox-debug:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "15901:5900"

  chrome:
    image: selenium-chinese/node-chrome-debug:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "15900:5900"

  hub:
    image: selenium/hub:3.9.1-actinium
    ports:
      - "4444:4444"
